spring.application.name=ApplyMate

server.port=9090

# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/applymate_db

# Credentials
spring.datasource.username=root
spring.datasource.password=Pass@venu

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Dialect (optional in latest versions, auto-detected)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
